### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by kssoz** [freifunkks/meshviewer#4] opened 2015-11-25 23:41 UTC
There are strange (glitchy) node shadows in the dark themed mesh view. 
Also the dark theme does not match with the [light themed website](https://freifunk-kassel.de/Karte).

Possible solutions: 
- default light theme with extra dark theme button
- delete shadows

**Comment by jplatte** [comment] 2015-11-26 00:03
I don't see a problem with the dark mesh view inside a light themed website.
Concerning the shadows: I don't see anything like that, and it's definitely not specific to our fork. Could you create a screenshot?

Also, I didn't close this issue because I just discovered upstream isn't maintained anymore. There seem to be a lot of other forks though and I won't just work on this without coordination with them. I'm not sure what I'll do with the other issues, for now I'll leave them as they are.

**Comment by kssoz** [comment] 2015-11-26 00:36
![glitchdarktheme](https://cloud.githubusercontent.com/assets/3306219/11412510/1f9392fc-93de-11e5-890c-f1a176c3f236.jpg)

**Comment by jplatte** [comment] 2015-11-26 01:54
Okay, I double-checked and this doesn't happen for me, not in Firefox and not in Chromium. Which browser are you using, and can you reproduce it across multiple browsers / systems?

**Comment by kssoz** [comment] 2015-11-26 09:49
Firefox 41.0.2 Win7

**Comment by jplatte** [comment] 2015-11-26 13:18
Okay, well I guess you just shouldn't update Firefox until we meet in person the next time, because I have no clue how else to debug this. Might even be a WebGL rendering issue or something like that.

**Comment by jplatte** [comment] 2015-12-15 03:33
@kssoz Do you think this issue can be closed? I don't think anything can be done in the meshviewer to fix these rendering bugs and the dark theme also is a design decision, and would take time to revert. Unless you really have a problem with the dark theme and want to try to convince me that switching back to the old theme is a good idea, I think we can close this.

**Comment by jplatte** [comment] 2016-01-20 02:03
Closing due to no activity and actual issue not being reproducable.

**Closed by jplatte** 2016-01-20 02:03 UTC
